### ISSUE TITLE
Create binaries

### ISSUE THREAD

**Issue by bussmann** [ComputationalRadiationPhysics/olav#4]
Although you provide information on how to make Olav, it would be great to have pre-bulit binaries for easier distribution and download (mos Olav users should not be familiar with building a project).

**Comment by theZiz** [comment]
Yes. I just finished an installer for Windows, which André tested and which works. However he also gave me a small to do (issue #1, #2 and #3 ;) ). When I implemented this (especially for the TdoL) I will make some ready to use window installer and debian package.

The question is: Where to distribute them? Just adding them to the repository or better to our group page at the hzdr website?

**Comment by theZiz** [comment]
Done: https://github.com/ComputationalRadiationPhysics/olav/releases/tag/v1.0.1
